version: "3.3"

services:

  server:
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - variables.env
    build:
      context: ./
    ports:
      - "4000:8000"
    volumes:
      - ./landing:/landing
      - farol_verde:/tmp/farol_verde_db
      - media:/landing/media
    container_name: farolwagtail
    depends_on:
      - farol_verde_db
    entrypoint: ["/bin/bash", "run.sh"]

  farol_verde_db:
    env_file:
      - variables.env
    image: postgres:13.1
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 10s
      timeout: 45s
      retries: 10
    expose:
      - "5656"
    volumes:
      - backups:/var/lib/postgresql/data
    container_name: farol_verde_db
    command: -p 5656
    ports:
      - "5656:5656"

  tests:
    image: cypress/included:10.7.0
    container_name: faroltests
    working_dir: /tests
    volumes:
      - ./tests:/tests
    depends_on:
      - server
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  farol_verde:
  media:
  backups:
