# Generated by Django 3.2.12 on 2022-07-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0002_form_site'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='survey_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='wagtailstreamforms.formsubmission'),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='id_autor',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='id_parlametria',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='id_serenata',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
