# Generated by Django 3.2.12 on 2022-07-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
