# Generated by Django 3.2.12 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20220728_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='party',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
