# Generated by Django 3.2.12 on 2022-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidatepage_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepage',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatepage',
            name='party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
