# Generated by Django 3.2.12 on 2022-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20220729_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='sobre',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
