# Generated by Django 3.2.12 on 2022-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_candidatepage_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='calculate_adhesion',
            field=models.BooleanField(default=True),
        ),
    ]
