# Generated by Django 3.2.12 on 2022-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_proposicao_calculate_adhesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorProposicao',
            fields=[
                ('id_parlamentar', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('proposicoes', models.ManyToManyField(related_name='autores', to='candidate.Proposicao')),
            ],
        ),
    ]
