# Generated by Django 3.2.12 on 2022-08-15 22:48

from django.db import migrations

from candidate.models import Proposicao


def change_propositions_about(apps, schema_editor):
    remove_from_adhesion_calc = 144582  # PL 4476/2020, Marco legal do gás
    Proposicao.objects.filter(id_externo=remove_from_adhesion_calc).update(
        calculate_adhesion=False
    )

    change_about = {
        "2190237": "Anistias no Código Florestal (MP 867/18)",  # MPV 867/2018
        "2233488": "MP da Grilagem (MP 910/19)",  # MPV 910/2019
        "46249": "PL do Veneno (PL 6299/02)",  # PL 6299/2002
        "2252589": "PL da Grilagem (PL 2633/20)",  # PL 2633/2020
        "946475": "Pagamento por Serviços Ambientais (derrubada de vetos PL 5028/19)",  # PL 5028/2019
        "2236765": "Mineração em Terras Indígenas (req. urgência PL 191/20)",  # PL 191/2020
        "2270639": "Mercado Brasileiro de Redução de Emissões (req. urgência PL 528/21)",  # PL 528/2021
    }

    for _id in change_about.keys():
        prop = Proposicao.objects.filter(id_externo=_id).first()

        if prop is not None:
            prop.sobre = change_about[_id]
            prop.save()


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0020_alter_candidatepage_opinions"),
    ]

    operations = [
        migrations.RunPython(change_propositions_about),
    ]
