# Generated by Django 3.2.12 on 2022-08-16 11:18

from django.db import migrations

from candidate.models import Proposicao


def change_propositions_about(apps, schema_editor):
    change_about = {
        "257161": "PL Licenciamento Ambiental (PL 3.729/04)",  # PL 3729/2004
        "2199215": "PL APP Urbana (PL 2.510/19)",  # PL 2510/2019
    }

    for _id in change_about.keys():
        prop = Proposicao.objects.filter(id_externo=_id).first()

        if prop is not None:
            prop.sobre = change_about[_id]
            prop.save()


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0021_renomeia_pls"),
    ]

    operations = [
        migrations.RunPython(change_propositions_about),
    ]
