# Generated by Django 3.2.12 on 2022-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_set_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='show_convergency',
            field=models.BooleanField(default=True),
        ),
    ]
