# Generated by Django 3.2.12 on 2022-09-19 17:06

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_candidatepage_show_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
