# Generated by Django 3.2.12 on 2022-09-19 11:15

from django.db import migrations, models
from candidate.models import CandidatePage

hide_convergency = [90, 878, 4610, 90842, 105534, 123756, 141401, 141480, 141552,
                    160517, 204433, 207309, 214865, 219585, 219592,
                    204563, 122466, None]

def set_convergency(apps, schema_editor):
    live_candidates = CandidatePage.objects.all().live()
    for candidate in live_candidates:
        is_show = candidate.id_autor not in hide_convergency
        candidate.show_convergency = is_show
        candidate.save()

def unset_convergency(apps, schema_editor):
    live_candidates = CandidatePage.objects.all().live()
    for candidate in live_candidates:
        candidate.show_convergency = None
        candidate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_candidatepage_show_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepage',
            name='show_convergency',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_convergency, unset_convergency),
    ]
