# Generated by Django 3.2.12 on 2022-09-20 20:11

from candidate.models import Proposicao, CasaChoices
from django.db import migrations


def change_proposition_about_name(apps, schema_editor):
    proposition = Proposicao.objects.filter(
        id_externo=132208, casa=str(CasaChoices.SENADO)
    ).first()

    if proposition is None:
        print("Proposition not found!!!")
        return

    proposition.sobre = "Acesso Água Potável como Direito Fundamental (PEC 04/2018)"
    proposition.save()

def change_proposition_about_name_rollback(apps, scheme_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0028_candidatepage_show_social_media"),
    ]

    operations = [
        migrations.RunPython(
            change_proposition_about_name, change_proposition_about_name_rollback
        )
    ]
