# Generated by Django 3.2.12 on 2022-08-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0003_alter_blogpost_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailimages.image",
            ),
        ),
    ]
