# Generated by Django 3.2.12 on 2022-06-08 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from wagtail.core.models import Page, Site
from home.models import LandingPage
import wagtailstreamforms


def create_set_home_page(apps, schema_editor):
    root = Page.get_first_root_node()

    home_page = LandingPage(title="Home")

    root.add_child(instance=home_page)
    root.save()

    site = Site.objects.get(id=1)
    site.root_page = home_page
    site.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0040_page_draft_title"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="LandingPage",
            name="clients",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "clients",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("link", wagtail.core.blocks.URLBlock(max_length=100)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="heading",
            field=wagtail.core.fields.RichTextField(
                default="<h1><b>Bem vindo ao boilerplate Wagtail da Pencil.</b></h1>"
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="surveys",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "form",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("form", wagtailstreamforms.blocks.FormChooserBlock()),
                                (
                                    "form_action",
                                    wagtail.core.blocks.CharBlock(
                                        help_text='The form post action. "" or "." for the current page or a url',
                                        required=False,
                                    ),
                                ),
                                (
                                    "form_reference",
                                    wagtailstreamforms.blocks.InfoBlock(
                                        help_text="This form will be given a unique reference once saved",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(create_set_home_page),
    ]
