# Generated by Django 3.2.12 on 2022-06-30 23:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
from wagtail.core.models import Page
from home.models import TermsPage

def create_terms_page(apps, schema_editor):
    home = Page.objects.get(title='Home')

    terms_page = TermsPage(title="Terms and Conditions", slug="terms-and-conditions")

    home.add_child(instance=terms_page)
    home.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0002_create_surveys_and_remove_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(default='lorem ipsum grandão')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(create_terms_page),
    ]
