# Generated by Django 3.2.12 on 2022-08-15 18:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_landingpage_popup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="popup",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "popup",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "active",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="Ativo", required=False
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        label="Título", required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.TextBlock(
                                        label="Texto do popup", required=False
                                    ),
                                ),
                            ],
                            max_num=1,
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
